# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision_frame.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12vision_frame.proto\"O\n\x0bVisionFrame\x12\x14\n\x08\x64istance\x18\x01 \x01(\x05:\x02-1\x12\x14\n\x08\x63\x65nter_x\x18\x02 \x01(\x05:\x02-1\x12\x14\n\x08\x63\x65nter_y\x18\x03 \x01(\x05:\x02-1')



_VISIONFRAME = DESCRIPTOR.message_types_by_name['VisionFrame']
VisionFrame = _reflection.GeneratedProtocolMessageType('VisionFrame', (_message.Message,), {
  'DESCRIPTOR' : _VISIONFRAME,
  '__module__' : 'vision_frame_pb2'
  # @@protoc_insertion_point(class_scope:VisionFrame)
  })
_sym_db.RegisterMessage(VisionFrame)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VISIONFRAME._serialized_start=22
  _VISIONFRAME._serialized_end=101
# @@protoc_insertion_point(module_scope)
