// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vision_frame.proto

package com.team1816.season.proto;

public final class VisionProto {
  private VisionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VisionFrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VisionFrame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 distance = 1 [default = -1];</code>
     * @return Whether the distance field is set.
     */
    boolean hasDistance();
    /**
     * <code>optional int32 distance = 1 [default = -1];</code>
     * @return The distance.
     */
    int getDistance();

    /**
     * <code>optional int32 center_x = 2 [default = -1];</code>
     * @return Whether the centerX field is set.
     */
    boolean hasCenterX();
    /**
     * <code>optional int32 center_x = 2 [default = -1];</code>
     * @return The centerX.
     */
    int getCenterX();

    /**
     * <code>optional int32 center_y = 3 [default = -1];</code>
     * @return Whether the centerY field is set.
     */
    boolean hasCenterY();
    /**
     * <code>optional int32 center_y = 3 [default = -1];</code>
     * @return The centerY.
     */
    int getCenterY();
  }
  /**
   * Protobuf type {@code VisionFrame}
   */
  public static final class VisionFrame extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VisionFrame)
      VisionFrameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VisionFrame.newBuilder() to construct.
    private VisionFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VisionFrame() {
      distance_ = -1;
      centerX_ = -1;
      centerY_ = -1;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VisionFrame();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VisionFrame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              distance_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              centerX_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              centerY_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.team1816.season.proto.VisionProto.internal_static_VisionFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.team1816.season.proto.VisionProto.internal_static_VisionFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.team1816.season.proto.VisionProto.VisionFrame.class, com.team1816.season.proto.VisionProto.VisionFrame.Builder.class);
    }

    private int bitField0_;
    public static final int DISTANCE_FIELD_NUMBER = 1;
    private int distance_;
    /**
     * <code>optional int32 distance = 1 [default = -1];</code>
     * @return Whether the distance field is set.
     */
    @java.lang.Override
    public boolean hasDistance() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 distance = 1 [default = -1];</code>
     * @return The distance.
     */
    @java.lang.Override
    public int getDistance() {
      return distance_;
    }

    public static final int CENTER_X_FIELD_NUMBER = 2;
    private int centerX_;
    /**
     * <code>optional int32 center_x = 2 [default = -1];</code>
     * @return Whether the centerX field is set.
     */
    @java.lang.Override
    public boolean hasCenterX() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 center_x = 2 [default = -1];</code>
     * @return The centerX.
     */
    @java.lang.Override
    public int getCenterX() {
      return centerX_;
    }

    public static final int CENTER_Y_FIELD_NUMBER = 3;
    private int centerY_;
    /**
     * <code>optional int32 center_y = 3 [default = -1];</code>
     * @return Whether the centerY field is set.
     */
    @java.lang.Override
    public boolean hasCenterY() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 center_y = 3 [default = -1];</code>
     * @return The centerY.
     */
    @java.lang.Override
    public int getCenterY() {
      return centerY_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, distance_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, centerX_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, centerY_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, distance_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, centerX_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, centerY_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.team1816.season.proto.VisionProto.VisionFrame)) {
        return super.equals(obj);
      }
      com.team1816.season.proto.VisionProto.VisionFrame other = (com.team1816.season.proto.VisionProto.VisionFrame) obj;

      if (hasDistance() != other.hasDistance()) return false;
      if (hasDistance()) {
        if (getDistance()
            != other.getDistance()) return false;
      }
      if (hasCenterX() != other.hasCenterX()) return false;
      if (hasCenterX()) {
        if (getCenterX()
            != other.getCenterX()) return false;
      }
      if (hasCenterY() != other.hasCenterY()) return false;
      if (hasCenterY()) {
        if (getCenterY()
            != other.getCenterY()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDistance()) {
        hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
        hash = (53 * hash) + getDistance();
      }
      if (hasCenterX()) {
        hash = (37 * hash) + CENTER_X_FIELD_NUMBER;
        hash = (53 * hash) + getCenterX();
      }
      if (hasCenterY()) {
        hash = (37 * hash) + CENTER_Y_FIELD_NUMBER;
        hash = (53 * hash) + getCenterY();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.team1816.season.proto.VisionProto.VisionFrame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.team1816.season.proto.VisionProto.VisionFrame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.team1816.season.proto.VisionProto.VisionFrame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.team1816.season.proto.VisionProto.VisionFrame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.team1816.season.proto.VisionProto.VisionFrame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.team1816.season.proto.VisionProto.VisionFrame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.team1816.season.proto.VisionProto.VisionFrame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.team1816.season.proto.VisionProto.VisionFrame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.team1816.season.proto.VisionProto.VisionFrame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.team1816.season.proto.VisionProto.VisionFrame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.team1816.season.proto.VisionProto.VisionFrame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.team1816.season.proto.VisionProto.VisionFrame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.team1816.season.proto.VisionProto.VisionFrame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VisionFrame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VisionFrame)
        com.team1816.season.proto.VisionProto.VisionFrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.team1816.season.proto.VisionProto.internal_static_VisionFrame_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.team1816.season.proto.VisionProto.internal_static_VisionFrame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.team1816.season.proto.VisionProto.VisionFrame.class, com.team1816.season.proto.VisionProto.VisionFrame.Builder.class);
      }

      // Construct using com.team1816.season.proto.VisionProto.VisionFrame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        distance_ = -1;
        bitField0_ = (bitField0_ & ~0x00000001);
        centerX_ = -1;
        bitField0_ = (bitField0_ & ~0x00000002);
        centerY_ = -1;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.team1816.season.proto.VisionProto.internal_static_VisionFrame_descriptor;
      }

      @java.lang.Override
      public com.team1816.season.proto.VisionProto.VisionFrame getDefaultInstanceForType() {
        return com.team1816.season.proto.VisionProto.VisionFrame.getDefaultInstance();
      }

      @java.lang.Override
      public com.team1816.season.proto.VisionProto.VisionFrame build() {
        com.team1816.season.proto.VisionProto.VisionFrame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.team1816.season.proto.VisionProto.VisionFrame buildPartial() {
        com.team1816.season.proto.VisionProto.VisionFrame result = new com.team1816.season.proto.VisionProto.VisionFrame(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.distance_ = distance_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.centerX_ = centerX_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.centerY_ = centerY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.team1816.season.proto.VisionProto.VisionFrame) {
          return mergeFrom((com.team1816.season.proto.VisionProto.VisionFrame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.team1816.season.proto.VisionProto.VisionFrame other) {
        if (other == com.team1816.season.proto.VisionProto.VisionFrame.getDefaultInstance()) return this;
        if (other.hasDistance()) {
          setDistance(other.getDistance());
        }
        if (other.hasCenterX()) {
          setCenterX(other.getCenterX());
        }
        if (other.hasCenterY()) {
          setCenterY(other.getCenterY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.team1816.season.proto.VisionProto.VisionFrame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.team1816.season.proto.VisionProto.VisionFrame) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int distance_ = -1;
      /**
       * <code>optional int32 distance = 1 [default = -1];</code>
       * @return Whether the distance field is set.
       */
      @java.lang.Override
      public boolean hasDistance() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 distance = 1 [default = -1];</code>
       * @return The distance.
       */
      @java.lang.Override
      public int getDistance() {
        return distance_;
      }
      /**
       * <code>optional int32 distance = 1 [default = -1];</code>
       * @param value The distance to set.
       * @return This builder for chaining.
       */
      public Builder setDistance(int value) {
        bitField0_ |= 0x00000001;
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 distance = 1 [default = -1];</code>
       * @return This builder for chaining.
       */
      public Builder clearDistance() {
        bitField0_ = (bitField0_ & ~0x00000001);
        distance_ = -1;
        onChanged();
        return this;
      }

      private int centerX_ = -1;
      /**
       * <code>optional int32 center_x = 2 [default = -1];</code>
       * @return Whether the centerX field is set.
       */
      @java.lang.Override
      public boolean hasCenterX() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 center_x = 2 [default = -1];</code>
       * @return The centerX.
       */
      @java.lang.Override
      public int getCenterX() {
        return centerX_;
      }
      /**
       * <code>optional int32 center_x = 2 [default = -1];</code>
       * @param value The centerX to set.
       * @return This builder for chaining.
       */
      public Builder setCenterX(int value) {
        bitField0_ |= 0x00000002;
        centerX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 center_x = 2 [default = -1];</code>
       * @return This builder for chaining.
       */
      public Builder clearCenterX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        centerX_ = -1;
        onChanged();
        return this;
      }

      private int centerY_ = -1;
      /**
       * <code>optional int32 center_y = 3 [default = -1];</code>
       * @return Whether the centerY field is set.
       */
      @java.lang.Override
      public boolean hasCenterY() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 center_y = 3 [default = -1];</code>
       * @return The centerY.
       */
      @java.lang.Override
      public int getCenterY() {
        return centerY_;
      }
      /**
       * <code>optional int32 center_y = 3 [default = -1];</code>
       * @param value The centerY to set.
       * @return This builder for chaining.
       */
      public Builder setCenterY(int value) {
        bitField0_ |= 0x00000004;
        centerY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 center_y = 3 [default = -1];</code>
       * @return This builder for chaining.
       */
      public Builder clearCenterY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        centerY_ = -1;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VisionFrame)
    }

    // @@protoc_insertion_point(class_scope:VisionFrame)
    private static final com.team1816.season.proto.VisionProto.VisionFrame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.team1816.season.proto.VisionProto.VisionFrame();
    }

    public static com.team1816.season.proto.VisionProto.VisionFrame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<VisionFrame>
        PARSER = new com.google.protobuf.AbstractParser<VisionFrame>() {
      @java.lang.Override
      public VisionFrame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VisionFrame(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VisionFrame> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VisionFrame> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.team1816.season.proto.VisionProto.VisionFrame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisionFrame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VisionFrame_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022vision_frame.proto\"O\n\013VisionFrame\022\024\n\010d" +
      "istance\030\001 \001(\005:\002-1\022\024\n\010center_x\030\002 \001(\005:\002-1\022" +
      "\024\n\010center_y\030\003 \001(\005:\002-1B(\n\031com.team1816.se" +
      "ason.protoB\013VisionProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_VisionFrame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VisionFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VisionFrame_descriptor,
        new java.lang.String[] { "Distance", "CenterX", "CenterY", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
